arch:
  - amd64
  - ppc64le
language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x

before_install:
  - go get golang.org/x/lint/golint

before_script:
  - go vet ./...
  - golint ./...

script:
  - go test -v ./...
