language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.15.x
  - 1.16.x

before_install:
  - go get golang.org/x/lint/golint

before_script:
  - go vet ./...
  - golint ./...

script:
  - go test -v ./...
